#!/bin/sh
# Copyright 2026 edcsnt. All rights reserved.

quote() {
	q= s= v=$1
	shift
	for p
	do
		q=$q$s\'
		while :
		do
			case $p in *\'*) ;; *) break; esac
			q="$q${p%%\'*}'\\''"
			p=${p#*\'}
		done
		q=$q$p\'
		case $s in '') s=\ ; esac
	done
	eval $v=\$q
}
